name: linting, testing and building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies
        run: npm install
      - name: Building the project
        run: npm run build:prod:client
      - name: Checking TypeScript
        run: npm run check:ts
      - name: Checking CSS
        run: npm run check:css
      - name: Checking formatting
        run: npm run check:formatting
      - name: Unit testing
        run: npm run test:unit:client
